//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospitalMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int Id { get; set; }
        public int AppointmentId { get; set; }
        public string Notes { get; set; }
        public string Medicines { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
